export const csetopics = [
  {
    topics: [
      {
        title: "Algorithms",
        url: "algorithms",
        subtopics: [
          { title: "Asymptotic Notation", url: "asymptotic-notation" },
          { title: "Recurrence Relation", url: "recurrence-relation" },
          { title: "Divide and Conquer", url: "divide-and-conquer" },
          { title: "Sorting", url: "sorting" },
          { title: "Greedy Technique", url: "greedy-technique" },
          { title: "Minimum Spanning Tree", url: "minimum-spanning-tree" },
          { title: "Shortest Path", url: "shortest-path" },
          { title: "Graph Traversal", url: "graph-traversal" },
          { title: "Dynamic Programming", url: "dynamic-programming" },
        ],
      },
      {
        title: "Data Structure",
        url: "data-structure",
        subtopics: [
          { title: "Array", url: "array" },
          { title: "Link List", url: "link-list" },
          { title: "Stack", url: "stack" },
          { title: "Queue", url: "queue" },
          { title: "Binary Tree", url: "binary-tree" },
          { title: "Binary Search Tree", url: "binary-search-tree" },
          { title: "AVL Tree", url: "avl-tree" },
          { title: "B Tree", url: "b-tree" },
          { title: "B+ Tree", url: "b-plus-tree" },
          { title: "Heap Tree", url: "heap-tree" },
          { title: "n-ary Tree", url: "n-ary-tree" },
          { title: "Hashing", url: "hashing" },
        ],
      },
      {
        title: "C Programming",
        url: "c-programming",
        subtopics: [
          { title: "Arithmetic Operation", url: "arithmetic-operation" },
          { title: "Conditional Statement", url: "conditional-statement" },
          { title: "Loops", url: "loops" },
          { title: "Array and Pointer", url: "array-and-pointer" },
          { title: "Functions", url: "functions" },
        ],
      },
      {
        title: "Compiler Design",
        url: "compiler-design",
        subtopics: [
          { title: "Lexical Analysis", url: "lexical-analysis" },
          { title: "Parsing", url: "parsing" },
          {
            title: "Syntax-directed Translation",
            url: "syntax-directed-translation",
          },
          {
            title: "Intermediate Code Generation",
            url: "intermediate-code-generation",
          },
          { title: "Runtime Environment", url: "runtime-environment" },
          { title: "Matching", url: "matching" },
        ],
      },
      {
        title: "Theory of Computation",
        url: "theory-of-computation",
        subtopics: [
          { title: "Regular Expression", url: "regular-expression" },
          { title: "Regular Grammar", url: "regular-grammar" },
          { title: "Regular Language", url: "regular-language" },
          { title: "Finite Automata", url: "finite-automata" },
          { title: "Context Free Grammar", url: "context-free-grammar" },
          { title: "Context Free Language", url: "context-free-language" },
          { title: "Push-down Automata", url: "push-down-automata" },
          { title: "Recursive Language", url: "recursive-language" },
          { title: "Turing Machine", url: "turing-machine" },
          { title: "Undecidability", url: "undecidability" },
        ],
      },
      {
        title: "Operating System",
        url: "operating-system",
        subtopics: [
          { title: "Process", url: "process" },
          { title: "CPU Scheduling", url: "cpu-scheduling" },
          { title: "Process Synchronization", url: "process-synchronization" },
          { title: "Deadlock", url: "deadlock" },
          { title: "Memory Management", url: "memory-management" },
          { title: "File System", url: "file-system" },
          { title: "Disk Scheduling", url: "disk-scheduling" },
          { title: "System Call", url: "system-call" },
          { title: "Thread", url: "thread" },
        ],
      },
      {
        title: "Computer Network",
        url: "computer-network",
        subtopics: [
          { title: "OSI Layer", url: "osi-layer" },
          { title: "Physical Layer", url: "physical-layer" },
          { title: "Data Link Layer", url: "data-link-layer" },
          { title: "Network Layer Protocol", url: "network-layer-protocol" },
          {
            title: "Transport Layer Protocol",
            url: "transport-layer-protocol",
          },
          {
            title: "Application Layer Protocols",
            url: "application-layer-protocols",
          },
          { title: "Network Security", url: "network-security" },
        ],
      },
      {
        title: "Computer Organization",
        url: "computer-organization",
        subtopics: [
          { title: "Machine Instruction", url: "machine-instruction" },
          { title: "Addressing Modes", url: "addressing-modes" },
          {
            title: "ALU Data Path and Control Unit",
            url: "alu-data-path-and-control-unit",
          },
          { title: "IO Interface", url: "io-interface" },
          { title: "Interrupt", url: "interrupt" },
          { title: "Pipeline Processor", url: "pipeline-processor" },
          { title: "Cache Memory", url: "cache-memory" },
          { title: "Secondary Storage", url: "secondary-storage" },
          { title: "Memory Chip Design", url: "memory-chip-design" },
        ],
      },
      {
        title: "Database Management System",
        url: "database-management-system",
        subtopics: [
          { title: "ER Model", url: "er-model" },
          { title: "Relational Schema", url: "relational-schema" },
          { title: "Relational Algebra", url: "relational-algebra" },
          { title: "Normal Form", url: "normal-form" },
          { title: "Transactions", url: "transactions" },
          { title: "Integrity Constraints", url: "integrity-constraints" },
          { title: "SQL", url: "sql" },
          { title: "Tuple Calculus", url: "tuple-calculus" },
          { title: "File System", url: "file-system" },
        ],
      },
      {
        title: "Discrete Mathematics",
        url: "discrete-mathematics",
        subtopics: [
          { title: "Propositional Logic", url: "propositional-logic" },
          { title: "Set Theory", url: "set-theory" },
          { title: "Relation", url: "relation" },
          { title: "Function", url: "function" },
          { title: "Lattice", url: "lattice" },
          { title: "Group Theory", url: "group-theory" },
          { title: "Graph Theory", url: "graph-theory" },
          { title: "Planar Graph", url: "planar-graph" },
          { title: "Combination", url: "combination" },
          { title: "Probability Theory", url: "probability-theory" },
          { title: "Recurrence", url: "recurrence" },
        ],
      },
      {
        title: "Digital Logic",
        url: "digital-logic",
        subtopics: [
          { title: "Number System", url: "number-system" },
          { title: "Boolean Algebra", url: "boolean-algebra" },
          { title: "Combinational Circuit", url: "combinational-circuit" },
          { title: "Sequential Circuit", url: "sequential-circuit" },
        ],
      },
      {
        title: "Engineering Mathematics",
        url: "engineering-mathematics",
        subtopics: [
          { title: "Linear Algebra", url: "linear-algebra" },
          { title: "Calculus", url: "calculus" },
          { title: "Numerical Method", url: "numerical-method" },
        ],
      },
      {
        title: "Only For ISRO CSE",
        url: "only-for-isro-cse",
        subtopics: [
          { title: "Software Engg.", url: "software-engg" },
          { title: "Web Technology", url: "web-technology" },
        ],
      },
    ],
  },
];
